<?php include 'hd.php';?>
<main role="main" class="main-content">
  <div class="container-fluid">
    <div class="row justify-content-center">
      <div class="col-12">
        <div class="card shadow mb-4">
          <div class="card-header bg-primary text-white">
            <h4 class="mb-0">Bank Deposit Terms and Conditions</h4>
          </div>

          <div class="card-body">
            <p class="text-muted">
              These Terms and Conditions govern all client deposits made through bank accounts, mobile payments, or directly at the cashier/recovery desk within our rental and payment management system. 
              By completing a deposit, you acknowledge that you have read, understood, and agreed to the terms outlined below.
            </p>

            <hr>

            <h5 class="mt-4 text-primary">1. Deposit Process</h5>
            <ul>
              <li>Clients may deposit funds via partner banks, approved mobile payment channels, or directly at our cashier/recovery office.</li>
              <li>Each deposit must reference a valid system-generated code or invoice number to ensure proper allocation of funds.</li>
              <li>Deposits made without a valid reference code may experience processing delays or rejection until verified manually.</li>
            </ul>

            <h5 class="mt-4 text-primary">2. Deposit Recording and Confirmation</h5>
            <ul>
              <li>Once the deposit is received, it is automatically recorded in the system under the client’s profile and associated property or contract.</li>
              <li>Clients will receive an automatic SMS notification confirming the amount, date, and payment reference once the transaction is successfully processed.</li>
              <li>In case of system downtime, SMS confirmation may be delayed but will still be sent after successful synchronization.</li>
            </ul>

            <h5 class="mt-4 text-primary">3. Role of Cashiers and Recovery Officers</h5>
            <ul>
              <li>Cashiers or recovery officers are responsible for accurately entering deposit details into the system and verifying client payment slips or transaction codes.</li>
              <li>No manual adjustment or refund can be made without system authorization and management approval.</li>
              <li>All deposits handled by staff are subject to internal audit and verification for accuracy and compliance.</li>
            </ul>

            <h5 class="mt-4 text-primary">4. Client Responsibility</h5>
            <ul>
              <li>Clients must keep their bank slip, payment confirmation, or transaction message until the system confirms receipt.</li>
              <li>Incorrect or incomplete payment references are the client’s responsibility and may result in delayed updates or unallocated funds.</li>
              <li>It is the client’s duty to ensure their contact number on record is valid to receive SMS notifications.</li>
            </ul>

            <h5 class="mt-4 text-primary">5. Refunds and Adjustments</h5>
            <ul>
              <li>Refunds due to overpayment or error will be processed only after proper verification and approval by management.</li>
              <li>Refunds may take up to 5 working days, depending on the payment channel used.</li>
            </ul>

            <h5 class="mt-4 text-primary">6. System Notifications and SMS</h5>
            <ul>
              <li>All verified deposits trigger an automated SMS message containing:
                <ul>
                  <li>Deposit reference number</li>
                  <li>Amount paid</li>
                  <li>Date and time of transaction</li>
                  <li>Property or account credited</li>
                </ul>
              </li>
              <li>SMS notifications are for confirmation purposes only and do not replace official receipts generated by the system.</li>
            </ul>

            <h5 class="mt-4 text-primary">7. Disputes</h5>
            <ul>
              <li>Any dispute related to a bank deposit must be reported within <strong>48 hours</strong> of the transaction by presenting proof of payment.</li>
              <li>Unreported disputes beyond this period may not qualify for correction or refund.</li>
            </ul>

            <h5 class="mt-4 text-primary">8. Acceptance</h5>
            <p>
              By completing a deposit, the client confirms that they accept these Terms and Conditions and authorize the company to record and process the payment as per system procedures.
            </p>

            <div class="alert alert-info mt-4">
              <strong>Note:</strong> Always verify your payment details before submitting. The system will not be responsible for deposits made to wrong accounts or using incorrect reference codes.
            </div>
          </div>
        </div>

        <div class="text-center mb-4">
          <a href="javascript:history.back()" class="btn btn-secondary">
            <i class="fe fe-arrow-left"></i> Go Back
          </a>
        </div>
      </div>
    </div>
  </div>
</main>

